package com.cheer.mybatis.mapper;

import com.cheer.mybatis.model.IFinance;
import java.util.List;

public interface IFinanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_finance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_finance
     *
     * @mbggenerated
     */
    int insert(IFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_finance
     *
     * @mbggenerated
     */
    IFinance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_finance
     *
     * @mbggenerated
     */
    List<IFinance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_finance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IFinance record);
}