package com.cheer.mybatis.mapper;

import com.cheer.mybatis.model.ILeaveDay;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ILeaveDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_leave_day
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_leave_day
     *
     * @mbggenerated
     */
    int insert(ILeaveDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_leave_day
     *
     * @mbggenerated
     */
    ILeaveDay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_leave_day
     *
     * @mbggenerated
     */
    List<ILeaveDay> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_leave_day
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ILeaveDay record);
    
    BigDecimal countILeaveDay(@Param("empno")String empno, @Param("startTimeAsStr")String startTimeAsStr,
			@Param("endTimeAsStr")String endTimeAsStr);

	List<ILeaveDay> queryILeaveDayInPage(@Param("empno")String empno, @Param("startTimeAsStr")String startTimeAsStr,
			@Param("endTimeAsStr")String endTimeAsStr, @Param("start")int start,@Param("quantity")int quantity);

	BigDecimal querySumDaysByEmpno(@Param("empno")String empno, @Param("startTimeAsStr")String startTimeAsStr,
			@Param("endTimeAsStr")String endTimeAsStr);

	ILeaveDay queryILeaveDayByDateAndEmpno(ILeaveDay iLeaveDay);
}