package com.cheer.mybatis.mapper;

import com.cheer.mybatis.model.ISalary;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ISalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_salary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_salary
     *
     * @mbggenerated
     */
    int insert(ISalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_salary
     *
     * @mbggenerated
     */
    ISalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_salary
     *
     * @mbggenerated
     */
    List<ISalary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_salary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ISalary record);

	List<ISalary> queryISalaryInPage(@Param("iSalary")ISalary iSalary, @Param("start")int start, @Param("quantity")int quantity);

	Long countISalary(ISalary iSalary);

	ISalary queryISalaryByEmpnoAndYear(ISalary iSalary);
}