package com.cheer.mybatis.model;

import java.io.Serializable;
import java.util.Date;

import com.cheer.util.DateUtil;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table i_account_privilege
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class IAccountPrivilege implements Serializable{
    /**
     * id
    */
    private Integer id;

    /**
     * account_id
    */
    private Integer accountId;

    /**
     * privilege_id
    */
    private Integer privilegeId;

    /**
     * created_time
    */
    private Date createdTime;

    /**
     * created_by
    */
    private String createdBy;

    /**
     * update_time
    */
    private Date updateTime;

    /**
     * update_by
    */
    private String updateBy;

    /**
     * version
    */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_account_privilege.id
     *
     * @return the value of i_account_privilege.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_account_privilege.id
     *
     * @param id the value for i_account_privilege.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_account_privilege.account_id
     *
     * @return the value of i_account_privilege.account_id
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_account_privilege.account_id
     *
     * @param accountId the value for i_account_privilege.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_account_privilege.privilege_id
     *
     * @return the value of i_account_privilege.privilege_id
     *
     * @mbggenerated
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_account_privilege.privilege_id
     *
     * @param privilegeId the value for i_account_privilege.privilege_id
     *
     * @mbggenerated
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_account_privilege.created_time
     *
     * @return the value of i_account_privilege.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_account_privilege.created_time
     *
     * @param createdTime the value for i_account_privilege.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_account_privilege.created_by
     *
     * @return the value of i_account_privilege.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_account_privilege.created_by
     *
     * @param createdBy the value for i_account_privilege.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_account_privilege.update_time
     *
     * @return the value of i_account_privilege.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_account_privilege.update_time
     *
     * @param updateTime the value for i_account_privilege.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_account_privilege.update_by
     *
     * @return the value of i_account_privilege.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_account_privilege.update_by
     *
     * @param updateBy the value for i_account_privilege.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_account_privilege.version
     *
     * @return the value of i_account_privilege.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_account_privilege.version
     *
     * @param version the value for i_account_privilege.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    private String createdTimeAsStr;
	private String updateTimeAsStr;

	public String getCreatedTimeAsStr() {
		return DateUtil.dateFormat(this.createdTime, DateUtil.DATE_PATTERN);
	}

	public void setCreatedTimeAsStr(String createdTimeAsStr) {
		this.createdTimeAsStr = DateUtil.dateFormat(this.createdTime, DateUtil.DATE_PATTERN);
	}

	public String getUpdateTimeAsStr() {
		if(this.updateTime==null) {
			return "";
		}
		return DateUtil.dateFormat(this.updateTime, DateUtil.DATE_PATTERN);
	}

	public void setUpdateTimeAsStr(String updateTimeAsStr) {
		if(this.updateTime!=null) {
			this.updateTimeAsStr = DateUtil.dateFormat(this.updateTime, DateUtil.DATE_PATTERN);
		}else {
			this.updateTimeAsStr="";
		}
	}
}