package com.cheer.mybatis.model;

import java.io.Serializable;
import java.util.Date;

import com.cheer.util.DateUtil;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table i_code
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ICode implements Serializable{
    /**
     * id
    */
    private Integer id;

    /**
     * code_name
    */
    private String codeName;

    /**
     * code_type
    */
    private String codeType;

    /**
     * created_by
    */
    private String createdBy;

    /**
     * created_time
    */
    private Date createdTime;

    /**
     * update_time
    */
    private Date updateTime;

    /**
     * update_by
    */
    private String updateBy;

    /**
     * version
    */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_code.id
     *
     * @return the value of i_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_code.id
     *
     * @param id the value for i_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_code.code_name
     *
     * @return the value of i_code.code_name
     *
     * @mbggenerated
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_code.code_name
     *
     * @param codeName the value for i_code.code_name
     *
     * @mbggenerated
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_code.code_type
     *
     * @return the value of i_code.code_type
     *
     * @mbggenerated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_code.code_type
     *
     * @param codeType the value for i_code.code_type
     *
     * @mbggenerated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_code.created_by
     *
     * @return the value of i_code.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_code.created_by
     *
     * @param createdBy the value for i_code.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_code.created_time
     *
     * @return the value of i_code.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_code.created_time
     *
     * @param createdTime the value for i_code.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_code.update_time
     *
     * @return the value of i_code.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_code.update_time
     *
     * @param updateTime the value for i_code.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_code.update_by
     *
     * @return the value of i_code.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_code.update_by
     *
     * @param updateBy the value for i_code.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_code.version
     *
     * @return the value of i_code.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_code.version
     *
     * @param version the value for i_code.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    private String createdTimeAsStr;
	private String updateTimeAsStr;

	public String getCreatedTimeAsStr() {
		return DateUtil.dateFormat(this.createdTime, DateUtil.DATE_PATTERN);
	}

	public void setCreatedTimeAsStr(String createdTimeAsStr) {
		this.createdTimeAsStr = DateUtil.dateFormat(this.createdTime, DateUtil.DATE_PATTERN);
	}

	public String getUpdateTimeAsStr() {
		if(this.updateTime==null) {
			return "";
		}
		return DateUtil.dateFormat(this.updateTime, DateUtil.DATE_PATTERN);
	}

	public void setUpdateTimeAsStr(String updateTimeAsStr) {
		if(this.updateTime!=null) {
			this.updateTimeAsStr = DateUtil.dateFormat(this.updateTime, DateUtil.DATE_PATTERN);
		}else {
			this.updateTimeAsStr="";
		}
	}
}