package com.cheer.mybatis.model;

import java.io.Serializable;
import java.util.Date;

import com.cheer.util.DateUtil;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table i_finance
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class IFinance implements Serializable{
    /**
     * id
    */
    private Integer id;

    /**
     * fund_name
    */
    private String fundName;

    /**
     * payer
    */
    private String payer;

    /**
     * payee
    */
    private String payee;

    /**
     * amount
    */
    private Long amount;

    /**
     * pay_time
    */
    private Date payTime;

    /**
     * kind
    */
    private String kind;

    /**
     * created_by
    */
    private String createdBy;

    /**
     * created_time
    */
    private Date createdTime;

    /**
     * update_time
    */
    private Date updateTime;

    /**
     * update_by
    */
    private String updateBy;

    /**
     * version
    */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.id
     *
     * @return the value of i_finance.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.id
     *
     * @param id the value for i_finance.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.fund_name
     *
     * @return the value of i_finance.fund_name
     *
     * @mbggenerated
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.fund_name
     *
     * @param fundName the value for i_finance.fund_name
     *
     * @mbggenerated
     */
    public void setFundName(String fundName) {
        this.fundName = fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.payer
     *
     * @return the value of i_finance.payer
     *
     * @mbggenerated
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.payer
     *
     * @param payer the value for i_finance.payer
     *
     * @mbggenerated
     */
    public void setPayer(String payer) {
        this.payer = payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.payee
     *
     * @return the value of i_finance.payee
     *
     * @mbggenerated
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.payee
     *
     * @param payee the value for i_finance.payee
     *
     * @mbggenerated
     */
    public void setPayee(String payee) {
        this.payee = payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.amount
     *
     * @return the value of i_finance.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.amount
     *
     * @param amount the value for i_finance.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.pay_time
     *
     * @return the value of i_finance.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.pay_time
     *
     * @param payTime the value for i_finance.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.kind
     *
     * @return the value of i_finance.kind
     *
     * @mbggenerated
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.kind
     *
     * @param kind the value for i_finance.kind
     *
     * @mbggenerated
     */
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.created_by
     *
     * @return the value of i_finance.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.created_by
     *
     * @param createdBy the value for i_finance.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.created_time
     *
     * @return the value of i_finance.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.created_time
     *
     * @param createdTime the value for i_finance.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.update_time
     *
     * @return the value of i_finance.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.update_time
     *
     * @param updateTime the value for i_finance.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.update_by
     *
     * @return the value of i_finance.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.update_by
     *
     * @param updateBy the value for i_finance.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_finance.version
     *
     * @return the value of i_finance.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_finance.version
     *
     * @param version the value for i_finance.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    private String createdTimeAsStr;
	private String updateTimeAsStr;

	public String getCreatedTimeAsStr() {
		return DateUtil.dateFormat(this.createdTime, DateUtil.DATE_PATTERN);
	}

	public void setCreatedTimeAsStr(String createdTimeAsStr) {
		this.createdTimeAsStr = DateUtil.dateFormat(this.createdTime, DateUtil.DATE_PATTERN);
	}

	public String getUpdateTimeAsStr() {
		if(this.updateTime==null) {
			return "";
		}
		return DateUtil.dateFormat(this.updateTime, DateUtil.DATE_PATTERN);
	}

	public void setUpdateTimeAsStr(String updateTimeAsStr) {
		if(this.updateTime!=null) {
			this.updateTimeAsStr = DateUtil.dateFormat(this.updateTime, DateUtil.DATE_PATTERN);
		}else {
			this.updateTimeAsStr="";
		}
	}
}