package com.cheer.mybatis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.text.ParseException;
import java.util.Date;

import javax.validation.constraints.NotNull;

import com.cheer.util.DateUtil;
import com.cheer.validator.annotation.IsEmpno;
import com.cheer.validator.annotation.IsYear;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table i_salary
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ISalary implements Serializable{
    /**
     * id
    */
    private Integer id;

    /**
     * base_pay
    */
    @NotNull(message="{ISalary.basepay.empty}")
    private BigDecimal basePay;

    /**
     * bonus
    */
    private BigDecimal bonus;

    /**
     * merit
    */
    private BigDecimal merit;
    
    private BigDecimal sumSalary;
    
    private BigDecimal payed;
    
    private BigDecimal balance;

    /**
     * salary_year
    */
    @IsYear(message="{iSalary.year.pattern}")
    private String salaryYear;
    
    private String firstDayOfYear;
    
    private String endOfYear;
    /**
     * empno
    */
    @IsEmpno(message="staff.empno.pattern")
    private String empno;

    /**
     * created_by
    */
    private String createdBy;

    /**
     * created_time
    */
    private Date createdTime;

    /**
     * update_time
    */
    private Date updateTime;

    /**
     * update_by
    */
    private String updateBy;

    /**
     * version
    */
    private Integer version;
    
    private IStaff iStaff;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.id
     *
     * @return the value of i_salary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.id
     *
     * @param id the value for i_salary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.base_pay
     *
     * @return the value of i_salary.base_pay
     *
     * @mbggenerated
     */
    public BigDecimal getBasePay() {
        return basePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.base_pay
     *
     * @param basePay the value for i_salary.base_pay
     *
     * @mbggenerated
     */
    public void setBasePay(BigDecimal basePay) {
        this.basePay = basePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.bonus
     *
     * @return the value of i_salary.bonus
     *
     * @mbggenerated
     */
    public BigDecimal getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.bonus
     *
     * @param bonus the value for i_salary.bonus
     *
     * @mbggenerated
     */
    public void setBonus(BigDecimal bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.merit
     *
     * @return the value of i_salary.merit
     *
     * @mbggenerated
     */
    public BigDecimal getMerit() {
        return merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.merit
     *
     * @param merit the value for i_salary.merit
     *
     * @mbggenerated
     */
    public void setMerit(BigDecimal merit) {
        this.merit = merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.salary_year
     *
     * @return the value of i_salary.salary_year
     *
     * @mbggenerated
     */
    public String getSalaryYear() {
		return this.salaryYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.salary_year
     *
     * @param salaryYear the value for i_salary.salary_year
     *
     * @mbggenerated
     */
    public void setSalaryYear(String salaryYear) {
        this.salaryYear = salaryYear;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.empno
     *
     * @return the value of i_salary.empno
     *
     * @mbggenerated
     */
    public String getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.empno
     *
     * @param empno the value for i_salary.empno
     *
     * @mbggenerated
     */
    public void setEmpno(String empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.created_by
     *
     * @return the value of i_salary.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.created_by
     *
     * @param createdBy the value for i_salary.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.created_time
     *
     * @return the value of i_salary.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.created_time
     *
     * @param createdTime the value for i_salary.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.update_time
     *
     * @return the value of i_salary.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.update_time
     *
     * @param updateTime the value for i_salary.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.update_by
     *
     * @return the value of i_salary.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.update_by
     *
     * @param updateBy the value for i_salary.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_salary.version
     *
     * @return the value of i_salary.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_salary.version
     *
     * @param version the value for i_salary.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    private String createdTimeAsStr;
	private String updateTimeAsStr;

	public String getCreatedTimeAsStr() {
		return DateUtil.dateFormat(this.createdTime, DateUtil.DATE_PATTERN);
	}

	public void setCreatedTimeAsStr(String createdTimeAsStr) {
		this.createdTimeAsStr = DateUtil.dateFormat(this.createdTime, DateUtil.DATE_PATTERN);
	}

	public String getUpdateTimeAsStr() {
		if(this.updateTime==null) {
			return "";
		}
		return DateUtil.dateFormat(this.updateTime, DateUtil.DATE_PATTERN);
	}

	public void setUpdateTimeAsStr(String updateTimeAsStr) {
		if(this.updateTime!=null) {
			this.updateTimeAsStr = DateUtil.dateFormat(this.updateTime, DateUtil.DATE_PATTERN);
		}else {
			this.updateTimeAsStr="";
		}
	}

	public IStaff getiStaff() {
		return iStaff;
	}

	public void setiStaff(IStaff iStaff) {
		this.iStaff = iStaff;
	}

	public BigDecimal getSumSalary() {
		return sumSalary;
	}

	public void setSumSalary(BigDecimal sumSalary) {
		this.sumSalary = sumSalary;
	}

	public BigDecimal getPayed() {
		return payed;
	}

	public void setPayed(BigDecimal payed) {
		this.payed = payed;
	}

	public BigDecimal getBalance() {
		return balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public String getFirstDayOfYear() {
		if(this.salaryYear !=null && !"".equals(this.salaryYear)) {
			this.firstDayOfYear = this.salaryYear+"-01-01";
		}else {
			this.firstDayOfYear = null;
		}
		return firstDayOfYear;
	}

	public void setFirstDayOfYear(String firstDayOfYear) {
		if(this.salaryYear !=null && !"".equals(this.salaryYear)) {
			this.firstDayOfYear = this.salaryYear+"-01-01";
		}else {
			this.firstDayOfYear = null;
		}
	}

	public String getEndOfYear() {
		if(this.salaryYear !=null && !"".equals(this.salaryYear)) {
			this.endOfYear = this.salaryYear+"-12-31";
		}else {
			this.endOfYear = null;
		}
		return endOfYear;
	}

	public void setEndOfYear(String endOfYear) {
		if(this.salaryYear !=null && !"".equals(this.salaryYear)) {
			this.endOfYear = this.salaryYear+"-12-31";
		}else {
			this.endOfYear = null;
		}
	}
	
	
}